### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/obj-rs#1]
### TODOs
- [x] Documenting `OBJ`, `MTL` spec docs → [wiki](https://github.com/simnalamburt/obj-rs/wiki#development-documents)
- [x] Streaming
- [x] SIMD aware type → #9
- [x] Beautiful type structure → #9 
- [x] Beautiful code structure
- [x] ~~Triangulation~~
- [x] Dead-simple usage
- Informative error message with line number → #2
- [x] 100% API documentation
- [x] Well tested
- [x] Bump glium version
- [ ] Tidy `error` module
- [ ] Remove all uses of pointers
- [ ] Resolve all TODOs in source codes
- [ ] Opt-out serde by default
- [ ] Test "features" in GitHub Actions with feature matrix
- [ ] Full support of `OBJ`, `MTL` spec
- [ ] Multiple encoding support
- [ ] Parameter with whitespaces support
- [ ] Triangulation support

&nbsp;

obj specs:
- Official: https://www.martinreddy.net/gfx/3d/OBJ.spec
- Wikipedia: https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format
- FileFormat: https://www.fileformat.info/format/wavefrontobj/egff.htm

obj samples:
- http://people.sc.fsu.edu/~jburkardt/data/obj/obj.html
- http://graphics.cs.williams.edu/data/meshes.xml

obj parsers:
1. https://github.com/PistonDevelopers/wavefront_obj: Supports subset of `obj` spec
1. https://github.com/csherratt/obj: Supports subset of `obj` spec, lacks of documentations
1. https://github.com/syoyo/tinyobjloader: C++

mtl specs:
- Official: https://paulbourke.net/dataformats/mtl/
- Wikipedia: https://en.wikipedia.org/wiki/Wavefront_.obj_file#Material_template_library
- FileFormat: https://www.fileformat.info/format/material
